const OFFERING_FUNCTIONAL_AREAS = {
  procurement: [
    "Initial Users",
    "Enterprise Profile",
    "Legal Structures",
    "Financial Reporting Structures",
    "Organization Structures",
    "Workforce Structures",
    "Users and Security",
    "Purchasing Categories",
    "Suppliers",
    "Approval Management",
    "Procurement Foundation",
    "Items",
    "Purchasing Foundation",
    "Procurement Transaction Account Rules",
    "Transaction Tax",
    "External Purchase Prices",
    "Receiving",
    "Receipt Accounting",
    "Payables",
    "Payments",
    "Cash Management",
    "Supplier Incentives",
    "Compliance Checklists",
    "Application Extensions",
  ],
  "manufacturing and supply chain materials management": [
    "Initial Users",
    "Enterprise Profile",
    "Legal Structures",
    "Financial Reporting Structures",
    "Organization Structures",
    "Customers",
    "Suppliers",
    "Facilities",
    "Users and Security",
    "Items",
    "Carriers and Transit Times",
    "Catalogs",
    "Inventory Management",
    "Advanced Inventory Management",
    "Receiving",
    "Shipping",
    "Receipt Accounting",
    "Cost Accounting",
    "Cost and Profit Planning",
    "Landed Cost Management",
    "Intrastat Reporting",
    "Manufacturing Master Data",
    "Structures",
    "Supply Chain Collaboration",
    "Supply Chain Orchestration",
    "Maintenance Management",
    "Supply Chain Financial Flows",
    "Service Logistics",
    "Product Recall Management",
    "Sustainability",
    "Application Extensions",
  ],
};

function getOfferingFunctionalAreaNames(offeringName) {
  return OFFERING_FUNCTIONAL_AREAS[String(offeringName || "").trim().toLowerCase()] || [];
}

module.exports = { getOfferingFunctionalAreaNames };
